server:
  port: 8079

spring:
  datasource:
    #url: jdbc:h2:mem:mydb
    #username: sa
    #password: password
    #driverClassName: org.h2.Driver
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: 555
    #driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    #spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create